name: "Check Authorized Users"

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - "model-output/**"

jobs:
  check-authorization:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v5

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: "https://hubverse-org.r-universe.dev"

      - name: "Set Up R Dependencies"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: "devel"
          packages: |
            github::cdcgov/hubhelpr

      - name: "Get Changed Model Output Directories"
        id: get_changed_files_in_model_output
        uses: step-security/changed-files@v46
        with:
          path: model-output
          dir_names: "true"

      - name: "Check User Authorization"
        run: |
          changed_dirs <- strsplit("${{ steps.get_changed_files_in_model_output.outputs.all_modified_files }}", " ")[[1]]
          hubhelpr::check_authorized_users(changed_dirs, "${{ github.actor }}", ".")
        shell: Rscript {0}
