name: Pull Request Labeler
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v5
      - name: "Apply Labels"
        id: label-pr
        uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yaml"
          sync-labels: true
