name: "Update Authorized Users"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "model-metadata/*.yaml"
      - "model-metadata/*.yml"

jobs:
  update-users-list:
    if: ${{ github.repository_owner == 'CDCgov' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: "Generate Installation Token"
      id: get_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.CDCGOV_HUB_BOT_APP_ID }}
        private-key: ${{ secrets.CDCGOV_HUB_BOT_APP_KEY }}

    - name: "Checkout Code"
      uses: actions/checkout@v5

    - name: "Setup R"
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        extra-repositories: "https://hubverse-org.r-universe.dev"

    - name: "Set Up R Dependencies"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        pak-version: "devel"
        packages: |
          github::cdcgov/hubhelpr

    - name: "Update Authorized Users"
      run: "hubhelpr::update_authorized_users('.')"
      shell: Rscript {0}

    - name: "Set Date"
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: "Check For Changes"
      id: check_diff
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b update-authorized-users-${{ env.DATE }}
        git add auxiliary-data/authorized_users.json
        git diff --cached --exit-code auxiliary-data/authorized_users.json || echo "changed=true" >> $GITHUB_ENV

    - name: "Commit Changes"
      if: env.changed == 'true'
      run: |
        git commit -m "Update authorized users"
        git push origin update-authorized-users-${{ env.DATE }}

    - name: "Create Pull Request"
      if: env.changed == 'true'
      run: |
        gh pr create --base main --head update-authorized-users-${{ env.DATE }} --title "Update authorized users" --body "This PR updates the authorized users list based on the latest metadata."
      env:
        GH_TOKEN: ${{ steps.get_token.outputs.token }}
